const messages = [
  "See what apps know.",
  "We read the fine print.",
  "You get the real story.",
  "No jargon. Just facts.",
  "Summarized for real people.",
  "Simple answers. No surprises."
  ];

const appData = new Map([
  ["ChatGPT", { developer: "OpenAI", description: "Introducing ChatGPT for iOS: OpenAI's latest advancements at your fingertips.", filename: "ChatGPT.webp",detailedInfo: "The data ChatGPT collects is fairly extensive, covering your prompts and conversation history, any files you upload, and feedback you provide. Additionally, it automatically gathers technical details such as your IP address, device type, browser information, approximate location, and usage patterns like session duration and frequency of use. If you have an account, it also stores your email address and other registration details. <br><br> To better protect your privacy, regularly clear your conversation history and restrict access to your data thru the following settings:<br>Profile→Settings→Personalization, turn off: Memories<br>Profile→Settings→Data Controls, turn off: Improve the model for everyone"}],
  ["Threads", { developer: "Instagram Inc.", description: "Say more with Threads — Instagram's text-based conversation app.", filename: "Threads.webp",detailedInfo: "Instagram Threads collects a highly extensive range of personal data. This includes your profile information (name, email, account settings), content you create and share, activity and interaction data (such as who you communicate with, how often, and how you engage with posts), device and technical details (IP address, device type, operating system), location data, contacts, search history, and metadata. The app also tracks how you use its features and, if enabled, can access your location, motion, and battery status through features like Auto Status. Threads shares data across the Meta ecosystem and uses it for personalizing your experience and for commercial purposes, including targeted advertising. While there is no evidence that Meta sells your data directly to third parties, it does share information with partners and uses it extensively for advertising and analytics.<br><br>For greater privacy, consider alternatives like Mastodon or Bluesky for social networking, which are decentralized and collect minimal personal data. To reduce data collection within Threads, restrict app permissions for location and audio access, and turn off the Auto Status feature."}],
  ["Google", { developer: "Google", description: "Download the Google app to stay in the know about things that matter to you. ", filename: "Google.webp",detailedInfo:"Google’s app collects a highly extensive array of personal information. This includes account details (such as your name, email, and payment info), content you create or upload (emails, photos, documents, comments), device and technical data (IP address, device type, operating system, app/browser settings), location data (from GPS, IP address, Wi-Fi, and Bluetooth), and detailed records of your activity (search queries, watched videos, interactions with ads, purchase history, and communications). Google uses this information to provide and improve its services, personalize content and ads, measure performance, and protect users. While Google does not sell your personal information directly to third parties, it uses your data to deliver targeted advertising and shares some information with partners for analytics, advertising, and security purposes.<br><br>For privacy-conscious alternatives, consider using DuckDuckGo or Brave, as they are designed to minimize data collection. To reduce tracking within Google’s app, visit your Google Account’s privacy settings to pause or delete your Web & App Activity, Location History, and YouTube History. You can also manage ad personalization, limit app permissions (such as location and microphone access), use incognito browsing mode, and regularly review and clear your activity data."}],
  ["Google Maps", { developer: "Google", description: "Explore and navigate the world with confidence using Google Maps. " , filename: "Google Maps.webp",detailedInfo:"Google Maps collects a highly extensive range of personal data. This includes account details (such as your name, email, and phone number), information you provide directly (like saved locations or reviews), device and technical data (including device model, operating system, unique identifiers, and network information), log information (such as your search queries, IP address, browser type, and system activity), and precise location data (via GPS, Wi-Fi, Bluetooth, and cell towers). Google also gathers data on how you interact with the app, cookies and similar technologies, and may associate this information with your Google Account. While Google does not sell your personal information, it uses the data to personalize services and ads, and shares information with trusted partners for processing, analytics, and advertising purposes.<br><br>For privacy-conscious alternatives, consider using apps like OsmAnd or Magic Earth, which do not require an account and minimize data collection. Within Google Maps, you can reduce tracking by disabling Location History, limiting app permissions (such as location access to \"While Using the App\"), and regularly clearing your search and location history. On your device, review privacy settings to restrict background data and ad personalization. These steps help limit data collection and enhance your control over your location privacy."}],
  ["Microsoft Teams", { developer: "Microsoft Corporation", description: "Whether you're connecting with your community for an upcoming activity or working with teammates on a project, Microsoft Teams helps bring people together so that they can get things done.", filename: "Microsoft Teams.webp",detailedInfo:"Microsoft Teams collects a substantial amount of personal and usage data. This includes account details (such as name, email, username, and profile picture), meeting and chat content (messages, shared files, audio/video recordings, and transcriptions), device and technical data (IP address, device type, operating system), meeting activity (join/leave times, attendance), and usage analytics. Teams distinguishes between required data (essential for running and securing the service) and optional data (used to improve the product experience). Microsoft does not use Teams data to serve ads, does not track users for marketing, and does not sell your data to third parties. Data may be shared with service providers and the Microsoft ecosystem. Organizational administrators from your company/team may have access to user content and activity.<br><br>Within Teams, you can enhance privacy by limiting optional diagnostic data sharing, turning off camera and microphone when not needed, and being mindful about the content you share and record. On your device, restrict app permissions on location and contacts access."}],
  ["WhatsApp Messenger", { developer: "WhatsApp Inc.", description: "Message privately, make calls and share files with your friends, family and colleagues.", filename: "WhatsApp Messenger.webp",detailedInfo:"WhatsApp collects essential information to provide a secure and reliable messaging experience. This includes your account details (phone number, profile name, and photo), contacts (with your permission), device information, usage data, and location if you choose to share it. Importantly, all your messages and calls are protected with end-to-end encryption, ensuring that only you and the recipient can read or listen to them; WhatsApp itself cannot access this content. While WhatsApp collects some metadata to improve service quality and security, it does not sell your data. It shares limited information within the Meta family and with trusted partners to enhance features and maintain safety.<br><br>For users seeking even more privacy-focused options, apps like Signal and Threema offer minimal data collection and independent operation. Within WhatsApp, you can further protect your privacy by managing permissions (such as contacts and location), controlling who can see your profile information, disabling cloud backups if you prefer, and enabling two-step verification for added security."}],
  ["CapCut - Video Editor", { developer: "Bytedance Pte. Ltd", description: "CapCut offers easy-to-use video editing functions, free in-APP fonts and effects, free advanced features such as keyframe animation, smooth slow-motion, chroma key, and stabilization, to help you capture and snip moments.", filename: "CapCut - Video Editor.webp",detailedInfo:"CapCut Video Editor collects a wide range of personal data. This includes account information (such as email, phone number, date of birth, and linked social accounts), user content (photos, videos, audio, comments, and metadata), device information (model, operating system, unique identifiers, IP address, region, and network details), approximate location (based on SIM card and IP address), usage data (content viewed, engagement, frequency, and duration), clipboard data (with permission), and purchase/payment information if you use paid features. CapCut may also collect information from third-party services if you log in with them, and from your contacts if you sync them. The app uses cookies and similar technologies for analytics and advertising. CapCut shares data with service providers, business partners, and other entities within its corporate group for functionality, analytics, and marketing. It may also share information with advertising partners to deliver relevant ads, but there is no indication that it directly sells user data to third parties for unrelated marketing purposes.<br><br>For privacy-conscious alternatives, consider open-source or minimal-data apps like Kdenlive or Shotcut, which do not require accounts or extensive data collection. To reduce tracking in CapCut, limit the permissions you grant (such as access to contacts, clipboard, and location) and avoid linking third-party accounts."}],
  ["TikTok", { developer: "TikTok Ltd.", description: "TikTok is THE destination for mobile videos. On TikTok, short-form videos are exciting, spontaneous, and genuine. Whether you're a sports fanatic, a pet enthusiast, or just looking for a laugh, there's something for everyone on TikTok. ", filename: "TikTok.webp",detailedInfo:"TikTok’s data collection is extensive. It gathers a wide range of information from users, including account details (such as username, password, email, and phone number), user-generated content (videos, comments, messages), usage data (how you interact with the app, what you view, your search history), device information (device model, operating system, mobile carrier, IP address, device identifiers), location data (both coarse and precise geolocation, if enabled), and content shared by the user (including metadata from uploaded files). TikTok’s policy states that it may share user data with third-party partners for advertising and marketing purposes, and some data may be used to serve targeted ads or for analytics. While the company claims it does not “sell” personal data in the traditional sense, it does share user information with advertisers and other business partners for marketing and advertising, which can have similar privacy implications.<br><br>For privacy-conscious users, several alternative apps offer enhanced privacy controls or collect less data. Options include Firework, which emphasizes user privacy and doesn’t rely on follower counts or likes; Skylight and Bluesky, which use decentralized protocols to give users more control over their data; and Signal, which, while not a direct TikTok replacement, offers secure multimedia sharing. To reduce TikTok’s data collection, users can take several steps:<br>1) Set your account to private to control who can see your content.<br>2) Avoid sharing your phone contacts or linking social accounts.<br>3) Limit ad personalization in the app’s settings.<br>4) Disable location services for TikTok on your device."}],
  ["Shop: All your favorite brands", { developer: "Shopify Inc.", description: "Shop, track, and explore the latest trends in an all-in-one shopping app" , filename: "Shop - All your favorite brands .webp",detailedInfo:"The Shop app by Shopify collects a broad range of user data. This includes account details (such as name, email, and payment information), usage data (like purchase history, order status, and how you interact with the app), device information (including device type, operating system, and IP address), location data (if enabled), and any content you share or connect (such as linking your email to import shopping receipts or connecting with other marketplaces). Shopify uses this information to provide and personalize services, improve the app, and for security. The app shares user data with third parties(including service providers, analytics partners, and advertising platforms) for purposes such as marketing, advertising, and improving services. While Shopify does not state that it \"sells\" user data in the traditional sense, it does use and share data for advertising and marketing, and users can opt out of some personalized advertising features.<br><br>To reduce data collection in the Shop app, users can: set stricter privacy settings within the app (under Account > Settings > Data and Privacy), avoid linking third-party email accounts or other platforms, turn off location services for the app on their device, opt out of personalized ads where possible, and regularly review and update privacy preferences."}],
  ["Indeed Job Search", { developer: "Indeed Inc.", description: "Discover your next job opportunity on Indeed, the free job search app designed to connect you with better work anytime, anywhere.", filename: "Indeed Job Search.webp",detailedInfo:"Indeed collects a broad range of user data during the job search, application, and recruitment process. This includes account details (name, address, email, phone), application data (CV/resume, qualifications, references, cover letters, interview information), work eligibility (immigration status, visas), financial and government ID information (bank details, passport, social security number), links to online profiles (LinkedIn, portfolio sites), and, in some cases, demographic data (race, gender, disability status) and background check results. Device information and usage data, such as site activity and geolocation (city, zip code), are also collected. Indeed shares data with affiliates, employers, service providers, and marketers for recruitment, service improvement, and advertising. While Indeed states it does not “sell” personal data as defined by law, it does share information with third parties for targeted advertising and marketing purposes.<br><br>Privacy-conscious alternatives to Indeed include job boards like We Work Remotely, Escape the City, or using professional networks like LinkedIn with strict privacy settings. To reduce data collection on Indeed, users can avoid uploading sensitive documents unless necessary, limit the personal information shared in their profile, adjust privacy and ad settings within their account, and use browser privacy features (like tracker blockers)."}],
  ["Gmail - Email by Google", { developer: "Google", description: "Secure, smart, and easy to use email Get more done with Gmail. Now integrated with Google Chat, Google Meet, and more, all in one place.", filename: "Gmail - Email by Google.webp",detailedInfo:"The Gmail app collects extensive user data. This includes account details (name, email, phone number), usage data (email activity, contacts, interactions), device information (device type, operating system, IP address), location data (if enabled), and the actual content of emails and attachments. Gmail also gathers data from device sensors and may use information from your browsing history if you sync your Google account. While Google states it does not sell personal information, it does share user data with third parties for purposes like service improvement, analytics, and advertising. Gmail uses automated systems to scan emails for features like spam filtering. While it no longer shows ads based on email content, some data is still used for ad targeting and service personalization.<br><br>Privacy-conscious alternatives to Gmail include encrypted email services such as ProtonMail, Tutanota, and others that do not scan emails or use data for advertising. To reduce data collection in Gmail, users can: adjust privacy settings in their Google Account, limit third-party app access, avoid syncing unnecessary data, turn off location services, and regularly review account permissions."}],
  ["Whatnot: Shop, Sell, Connect", { developer: "Whatnot Inc.", description: "Whatnot is the largest live shopping platform in the US, UK, and Europe - we're a marketplace bringing millions together to shop, sell, and connect around the things they love. ", filename:"Whatnot - Shop, Sell, Connect.webp",detailedInfo:"The Whatnot app collects a somewhat wide range of user data, including personal information provided during purchases (name, address, email), payment details, and data automatically gathered from your device (such as IP address and browser or operating system type). The app may also collect information about your interactions with the platform. Whatnot uses this data to process transactions, provide services, and, with your permission, send marketing emails. The app does not sell personal data but may share it with third parties for payment processing, legal compliance, or marketing, only if you have given explicit consent for marketing purposes. Sensitive payment and address information is encrypted, and personal details are not shared between buyers and sellers.<br><br>To reduce data collection on Whatnot, users can avoid sharing unnecessary personal details, opt out of marketing emails, enable two-factor authentication, and regularly review app permissions on their device. Using the web version instead of the app and deleting unused accounts can also help limit tracking and data retention."}],
  ["Instagram", { developer: "Instagram, Inc.", description: "Little moments lead to big friendships. Share yours on Instagram. — From Meta", filename: "Instagram.webp",detailedInfo:"Instagram collects a vast amount of user data, including account details (name, email, phone number), usage data (interactions, posts, likes, comments, search history), device information (device type, operating system, IP address), location data (if enabled), and all content shared by the user (photos, videos, messages). Instagram, owned by Meta, shares this data with its parent company and third parties for targeted advertising, analytics, and service improvement. While Meta states it does not “sell” data in the traditional sense, it uses and shares user information extensively for marketing and advertising purposes across its platforms and with external partners.<br><br>Privacy-conscious alternatives to Instagram include Pixelfed, an open-source, ad-free, privacy-first photo sharing platform, and MeWe, which promises no ads or data selling. To reduce Instagram’s data collection, users can set their account to private, limit location access, stop syncing contacts, restrict app permissions (like camera, microphone, and photos), clear browsing and activity history, and turn off ad personalization and tracking in the app’s settings. Using Instagram through a mobile browser instead of the app and regularly reviewing privacy settings can further minimize tracking and data retention."}],
  ["Telegram Messenger", { developer: "Telegram FZ-LLC", description: "Pure instant messaging — simple, fast, secure, and synced across all your devices.",filename:"Telegram.webp",detailedInfo:"Telegram collects a limited set of user data compared to many messaging apps. The main information collected includes your phone number, basic account details (profile name, photo, username), contacts (if you choose to sync them), and messages or media shared in *cloud chats* (which are stored encrypted on Telegram’s servers). Device information (like IP address and app version) and limited metadata (such as login history and username changes) may also be collected for security and spam prevention. Secret chats use end-to-end encryption and are not stored on Telegram’s servers. Telegram does not require your real name, does not track your browsing, and does not collect unnecessary personal information. The app does not sell or share user data for marketing or advertising purposes. Sponsored messages in public channels are shown based on channel topics, not user data.<br><br>Privacy-conscious alternatives to Telegram include Signal and Session, which offer end-to-end encryption by default and collect minimal metadata. To reduce data collection on Telegram, avoid syncing contacts, use secret chats for sensitive conversations, limit sharing of personal details, manage bot permissions, and regularly review privacy settings in the app. You can also clear synced contacts and payment data from Telegram’s settings, and restrict location sharing and access to device features to further minimize tracking."}],
  ["Gauth: AI Study Companion", { developer: "GAUTHTECH PTE. LTD.", description: "Gauth is the #1 AI study companion powered by newest AI model! Trusted by millions of users, Gauth offers unlimited answers for all subjects. Try Gauth for all your learning needs!",filename:"Gauth.webp",detailedInfo:"The Gauth: AI Study Companion app collects a broad range of user data. This includes account details (such as contact information), identifiers, user content (like homework questions and uploads), usage data (how you interact with the app), device information (device IDs, operating system), and diagnostic data. The app may also collect location data if enabled. Some of this information is used to track users across apps and websites owned by other companies. Gauth states that it may share data with third parties for purposes such as analytics and marketing, but there is no indication that it sells personal data directly. Data is encrypted in transit, and users can request data deletion.<br><br>Privacy-conscious alternatives include using study apps like Socratic by Google or Photomath, which offer strong privacy controls, or relying on open-source educational resources. To reduce data collection on Gauth, users can avoid sharing unnecessary personal details, limit permissions (especially access to contacts and location), opt out of marketing communications, and regularly review privacy settings. Using the app without linking it to other accounts and periodically deleting unused data can further minimize tracking and data retention."}],
  ["Canva: AI Photo & Video Editor", { developer: "Canva", description: "Canva is an all-in-one visual communication platform that empowers the world to design",filename:"Canva.webp",detailedInfo:"Canva collects a broad amount of user data. This includes account details (such as name, email, phone number, profession, and address), usage data (how you interact with the app, search queries, and feedback), device information (device type, operating system, IP address), and location data for personalization, analytics, and advertising if enabled. Canva also collects all content you upload or create, such as designs, images, documents, and videos, along with related metadata. Information may also be received from third-party services if you link accounts or use social logins. Canva shares user data with third-party service providers for analytics, marketing, and to deliver personalized offers, but there is no indication it directly sells personal data. For Canva for Education, advertising and data use are more limited.<br><br>Privacy-conscious alternatives to Canva include open-source design tools like Penpot or desktop-based apps such as GIMP or Inkscape, which do not require cloud accounts or collect as much data. To reduce data collection on Canva, avoid linking third-party accounts, limit permissions (such as location access), regularly review privacy settings, and keep content private whenever possible. Users can also delete or download their data from Canva’s account settings and opt out of personalized marketing communications."}],
  ["Microsoft Authenticator", { developer: "Microsoft Corporation", description: "Use Microsoft Authenticator for easy, secure sign-ins for all your online accounts using multi-factor authentication, passwordless, or password autofill.",filename:"MicrosoftAuthenticator.webp",detailedInfo:"The Microsoft Authenticator app collects limited personal data compared to many other apps. It primarily gathers non-personally identifiable usage data, such as information about app operations and reliability, to help improve security and performance. Diagnostic log data, which may include personal details like email addresses or device info, is only sent to Microsoft if you choose to submit feedback. The app may also collect device information, app version, and, in some cases, location data for specific features, but you can control or disable location tracking in the settings. Microsoft does not sell personal data, but some information may be shared with third parties for analytics or required by your organization if you use the app for work. Users have control over what data is shared, and additional data sharing (such as usage analytics) is optional and can be turned off at any time.<br><br>To reduce data collection and tracking in Microsoft Authenticator, adjust privacy settings to limit data sharing, disable location access, avoid unnecessary third-party integrations, and only submit diagnostic logs when needed."}],
  ["Google Chrome", { developer: "Google", description: "Now more simple, secure and faster than ever. Get the best of Google Search, and easily sync your bookmarks and passwords with Chrome on your laptop. ",filename:"Google Chrome.webp",detailedInfo:"The Google Chrome app collects a significant amount of user data. This includes account details (such as name, email, and phone number if you sign in), usage data (browsing history, bookmarks, search queries, tabs, and autofill information), device information (device type, operating system, IP address), and location data if enabled. Chrome also collects content you interact with, such as extensions and downloads. If you enable sync with your Google Account, this personal information is stored on Google’s servers and used across devices. Google does not sell your personal information, but it shares data with third parties for analytics, service improvement, and advertising purposes, and uses your data to personalize ads and services across its platforms.<br><br>Privacy-conscious alternatives to Chrome include browsers like Mozilla Firefox, Brave, and DuckDuckGo, which focus on minimizing data collection and tracking. To reduce data collection in Chrome, use Incognito mode, disable sync, limit permissions for location and extensions, regularly clear browsing data, and adjust privacy settings in your Google Account. Installing reputable ad blockers and tracker blockers can further reduce tracking and data sharing."}],
  ["Max: Stream HBO, TV, & Movies", { developer: "WarnerMedia Global Digital Services, LLC", description: "The most talked about shows and movies featuring the worlds of HBO, the DC Universe, Adult Swim, A24, and beyond — plus live sports, breaking news, and more on Max.",filename:"Max.webp",detailedInfo:"The HBO Max app (now Max) collects a substantial amount of user data. This includes account details (such as email, name, and payment information), usage data (like watch history, search queries, and interactions with content), device information (device type, operating system, IP address, unique identifiers), and location data. The app also gathers information from your interactions with emails and notifications. HBO Max shares user data with affiliates, service providers, and third parties for analytics, personalized advertising, and service improvement. Some US residents can opt out of the sale or sharing of personal information for marketing purposes, but data is still used for targeted ads unless these settings are changed.<br><br>Privacy-conscious alternatives to HBO Max include streaming services that prioritize privacy, such as Kanopy or public library streaming options, which tend to collect less data. To reduce data collection on HBO Max, users can adjust privacy and cookie preferences in the app settings, opt out of marketing emails and targeted ads, limit app permissions (such as location access), and regularly review their privacy settings. Submitting a “Do Not Sell or Share” request and disabling app notifications can further minimize tracking and data sharing."}],
  ["Facebook", { developer: "Meta Platforms, Inc.", description: "Where real people propel your curiosity. Whether you're thrifting gear, showing a reel to that group who gets it, or sharing laughs over fun images reimagined by AI, Facebook helps you make things happen like no other social network.",filename:"Facebook.webp",detailedInfo:"The Facebook app collects extremely extensive user data. This includes account details (name, date of birth, email, phone number), all profile information, and every action performed on the platform such as posts, comments, likes, and messages. It also gathers detailed usage data (browsing history, engagement with content, friend connections), device information (phone brand, operating system, installed apps, device IDs, Wi-Fi and Bluetooth signals, IP address, and connected devices), location data (current and past locations), and metadata from uploaded files. Facebook tracks your behavior both on and off the app, including online purchases and browsing activity. The app shares and sells user data to third parties for targeted advertising, marketing, analytics, and even uses public posts and images to train Meta’s AI models.<br><br>Privacy-conscious alternatives to Facebook include decentralized social platforms like Mastodon or privacy-focused networks such as MeWe. To reduce data collection on Facebook, set your profile to private, limit the information you share, disable location access, restrict app permissions, avoid syncing contacts, clear activity and browsing history regularly, and opt out of ad personalization in settings. Consider using Facebook through a web browser with tracker blockers and review your privacy settings frequently to minimize tracking and data sharing."}],
  ["Spotify: Music and Podcasts", { developer: "Spotify", description: "With the Spotify app, you can explore an extensive library of music and podcasts for free. Curate the best playlists and stream millions of free songs, albums, and original podcasts on your phone or tablet. ",filename:"Spotify.webp",detailedInfo:"Spotify collects a substantial amount of user data. This includes account details (such as email address, phone number, date of birth, and gender), usage data (like search queries, streaming and browsing history, playlists, and interactions), device information (device type, operating system, IP address, and device sensor data such as movement or orientation), and location data if enabled. Spotify also collects content you share, such as playlists or social activity, and may receive additional information if you connect your account to other platforms like social media. Spotify does not directly sell personal data, but it shares user information with third-party marketing partners and uses it for targeted advertising and analytics purposes.<br><br>Privacy-conscious alternatives to Spotify include music services like Apple Music (with stricter privacy controls), Tidal, or open-source platforms such as Funkwhale. To reduce data collection on Spotify, users can adjust privacy and notification settings, opt out of tailored advertising in account privacy controls, use private listening sessions, limit permissions (such as location access), and avoid linking social media accounts."}],
  ["Walmart: Shopping & Savings", { developer: "Walmart", description: "The Walmart app is the easiest way to shop for everything on your list, including fresh groceries, household essentials, the latest tech and a lot more. ",filename:"Walmart.webp",detailedInfo:"The Walmart app collects an extensive range of personal data. This includes account details (name, email, phone number, address, government-issued IDs), usage data (purchase history, browsing and search activity, interactions with content, and ratings or reviews), device information (device type, operating system, IP address, unique identifiers, and app usage patterns), location data (including real-time and precise location), and content shared by the user (such as photos, audio, or video recordings). The app also gathers sensitive information like Social Security numbers, union membership status, and even biometric data if you use features like virtual try-on. Walmart shares data with more than 50 third parties for analytics, marketing, and advertising purposes, and there is no option for users to fully erase their data or prevent all forms of data sharing or tracking.<br><br>Privacy-conscious alternatives include shopping in-store with cash, using privacy-focused retailers, or shopping online with retailers that limit data collection. To reduce data collection and tracking in the Walmart app, avoid granting unnecessary permissions (like location or contacts), do not use features that require sensitive information, opt out of marketing communications, and regularly review privacy settings. Consider not linking the app to other accounts and periodically deleting unused account data where possible."}],
  ["Capital One Shopping: Save Now", { developer: "Wikibuy, LLC", description: "100% Free for everyone - no Capital One account required! Get free automatic coupons and exclusive savings on the go. Plus, get a free rewards bonus when you download the app and add the free tool to Safari.",filename:"CapitalOne Shopping.webp",detailedInfo:"The CapitalOne Shopping app collects a moderate amount of user data. This includes account details (such as email and login information), shopping behavior (products you view and purchase), browser and device information (device type, operating system, and IP address), and location data to help find localized deals. The app does not require or store sensitive financial information like bank account or credit card numbers, as payments are handled securely by third-party processors. CapitalOne Shopping shares some data with third parties for analytics, marketing, and to personalize deals, but it does not directly sell your personal information. Users can control certain data preferences and opt out of some data collection practices.<br><br>Privacy-conscious alternatives include shopping directly on retailer websites, using privacy-focused shopping extensions, or searching for deals manually. To reduce data collection in CapitalOne Shopping, avoid granting unnecessary permissions, limit location access, regularly review your privacy settings, and opt out of marketing communications."}],
  ["YouTube", { developer: "Google", description: "Get the official YouTube app on iPhones and iPads. See what the world is watching -- from the hottest music videos to what's popular in gaming, fashion, beauty, news, learning and more. ",filename:"Youtube.webp",detailedInfo:"The YouTube app collects a broad range of user data. This includes account details (such as your name and email if you sign in), usage data (search and watch history, recommendations, interactions, and content you upload), device information (device type, operating system, and IP address), and location data (estimated from your IP address or provided when uploading videos). YouTube also tracks how you interact with ads and content across the platform. While YouTube and Google do not sell your personal information, they do share data with third parties for analytics, service improvement, and to personalize ads and recommendations across Google services. Users have significant control over what data is collected and how it is used, including the ability to manage, download, or delete their data at any time.<br><br>Privacy-conscious alternatives to YouTube include decentralized video platforms like PeerTube or privacy-focused services such as Vimeo. To reduce data collection and tracking on YouTube, use Incognito mode, regularly clear your search and watch history, adjust privacy and ad personalization settings, limit location access, and avoid linking additional accounts. You can also manage what personal information is visible to others and use browser privacy tools or tracker blockers when accessing YouTube on the web."}],
  ["Uber - Request a ride", { developer: "Uber Technologies, Inc.", description: "Join the millions of riders who trust Uber for their everyday travel needs. Whether you're running an errand across town or exploring a city far from home, getting there should be easy.",filename:"Uber.webp",detailedInfo:"The Uber app collects a wide range of personal data. This includes account details (such as name, email, phone number, and payment information), usage data (trip history, order history, search history, and interactions within the app), device information (device type, operating system, IP address, and unique identifiers), location data (real-time and historical locations), and content shared by the user (such as ratings, feedback, and communications with drivers or support). Uber also collects data through cookies and related technologies. User data is shared with third-party service providers, ad partners, and business partners for analytics, personalized advertising, and service improvement, but Uber states it does not directly sell personal information.<br><br>Privacy-conscious alternatives to Uber include using local taxi services, public transportation, or ride-hailing apps that emphasize privacy and limit data collection. To reduce data collection and tracking in the Uber app, users can adjust privacy settings in the app to limit location sharing, disable unnecessary device permissions, opt out of personalized ads, and regularly review and update their privacy preferences. Users can also request access to, download, or delete their personal data through Uber’s Privacy Center, and minimize the information shared by not linking third-party accounts or using features that require additional data sharing."}],
  ["Microsoft Outlook", { developer: "Microsoft Corporation", description: "Outlook lets you bring all your email accounts and calendars in one convenient spot. Whether it's staying on top of your inbox or scheduling the next big thing, we make it easy to be your most productive, organised and connected self.",filename:"Microsoft Outlook.webp",detailedInfo:"The Microsoft Outlook app collects a broad and significant range of user data. This includes account details (such as email address, login credentials, and contacts), usage data (like email content, attachments, calendar events, and interactions within the app), device information (device type, operating system, IP address, and unique identifiers), and potentially location data. With the latest versions, all emails, attachments, and authentication details are stored and processed in Microsoft’s cloud infrastructure, even when connecting to third-party email providers. Microsoft shares user data with hundreds of third-party partners for purposes including analytics, product development, and personalized advertising. Both free and paid versions display ads and integrate with advertising partners, and users have limited ability to opt out of all data sharing. While Microsoft states compliance with regulations like GDPR, personal Outlook accounts may not receive the same data protection as enterprise accounts, and data may be stored or processed in multiple jurisdictions.<br><br>Privacy-conscious alternatives to Outlook include email services like Proton Mail, Tutanota, or self-hosted clients that do not rely on centralized cloud storage. To reduce data collection and tracking in Outlook, avoid connecting third-party email accounts, disable unnecessary permissions, use privacy controls to limit data sharing, and regularly review and update privacy settings."}],
  ["DoorDash - Food Delivery", { developer: "DoorDash, Inc.", description: "With more than 310,000 menus and 55,000+ grocery, convenience and retail stores across 4,000+ cities in the U.S., Canada, and Australia, DoorDash offers the greatest online selection of your favorite restaurants and stores, delivered wherever you are.",filename:"Doordash.webp",detailedInfo:"The DoorDash app collects a wide range of personal information. This includes account details (such as name, address, phone number, email, and payment information), identification documents and signatures for age-restricted products, usage data (order and transaction history, browsing activity, and interactions within the app), device information (IP address, device type, browser type), geolocation data, and content shared by the user (such as feedback, photos, audio, or video). DoorDash may also collect sensitive personal information like biometric data, and in some cases, information about your preferences, communications, and even browsing history. The app shares or sells categories of personal information—including identifiers, commercial information, and online activity—with third parties for analytics, marketing, and personalized advertising purposes. Data may also be disclosed to law enforcement or as required by law.<br><br>To reduce data collection and tracking in DoorDash, limit the permissions you grant (such as location or camera), avoid sharing sensitive information, opt out of marketing communications, and regularly review your privacy settings. Consider using the website instead of the app with browser tracker blockers."}],
  ["McDonald's", { developer: "McDonald's USA", description: "Get the app now to join MyMcDonald's Rewards and start earning points on your faves for free McDonald's. Plus, get exclusive deals and save time by ordering ahead in the app.",filename:"McDonalds.webp",detailedInfo:"The McDonald’s app collects a wide range of personal data. This includes account details (such as name, email, phone number, address, and payment information), usage data (order history, spending patterns, app interactions, and preferences), device information (device type, operating system, IP address), and precise location data if you enable location services. The app may also collect sensitive information like health data if you submit a related request, and it tracks behavioral and psychological trends, such as your ordering times and preferences. McDonald’s shares user data within its corporate group, with franchisees, suppliers, and marketing agencies for analytics, service improvement, and targeted advertising. While McDonald’s states it does not sell your data to third parties, sharing for advertising and analytics may be considered a sale under some privacy laws.<br><br>Privacy-conscious alternatives include ordering in person with cash, using local restaurants’ own apps with limited data collection, or choosing food delivery services that prioritize privacy. To reduce data collection and tracking in the McDonald’s app, limit permissions (especially for location), avoid saving sensitive information, opt out of marketing communications, and regularly review your privacy settings. You can also use the app without creating a profile where possible, clear your order history, and disable background app activity to further minimize data sharing and tracking."}],
  ["Meta AI", { developer: "Meta Platforms, Inc.", description: "Meet the new Meta AI app, your personal AI assistant that understands you. Get tailored answers, advice and inspiration as you go about your day.", filename:"Meta AI.webp",detailedInfo:"The Meta AI app collects an extensive range of personal data. This includes account details (such as your name, email, and information from linked Facebook or Instagram accounts), usage data (all chat transcripts, voice recordings, and interactions within the app), device information, and location data if enabled. The app also stores and analyzes the content you share, including sensitive topics, and creates a persistent “Memory” file about your interests and behaviors. By default, Meta AI retains all conversations and uses them to personalize responses, improve its AI, and potentially target you with ads across Meta platforms. Data from Meta AI can be shared with Facebook and Instagram, and your chats may be used to train future versions of Meta’s AI models. While Meta AI does not currently display ads, its privacy policy does not prevent future use of your data for advertising or marketing purposes, and there is no way to fully opt out of data collection or AI training.<br><br>To reduce data collection in Meta AI, avoid linking your Facebook or Instagram account, use the app without logging in when possible, regularly delete your chat history and Memory file, and refrain from sharing sensitive or personal information. Always review privacy settings, and consider using the web version without an account for maximum privacy."}],
  ["Cash App: Mobile Banking", { developer: "Block, Inc.", description: "Cash App is the easy way to spend, save, and invest your money.* Pay anyone in cash or bitcoin* instantly and enjoy Cash App's free Lightning Network transfers with compatible wallets. Start saving by rounding up your spare change to the nearest dollar or invest in stocks, ETFs, or bitcoin." ,filename:"Cash App.webp",detailedInfo:"The Cash App privacy policy shows that the app collects a large amount of personal data. This includes account details (name, email, phone number, address, date of birth, government-issued ID, Social Security number, and authentication credentials), financial information (bank account and payment card numbers), transaction data (when and where transactions occur, parties involved, payment amounts, and device used), device information (IP address, device type, and operating system), location data, and contacts information if you allow access. Cash App may also collect biometric data for identity verification and information about your intended payment recipients. While Cash App states it does not sell your personal information to third parties, it does share data with affiliates, service providers, and other third parties for analytics, service enhancement, and marketing purposes. Aggregated and anonymized data may also be shared, and users have limited options to opt out of all data sharing.<br><br>Privacy-conscious alternatives include using payment apps like Signal Payments or privacy-focused digital wallets, or making payments in person with cash. To reduce data collection and tracking in Cash App, avoid granting unnecessary permissions (such as contacts or location), do not upload sensitive documents unless required, regularly review and update privacy settings, and opt out of marketing communications where possible."}],
  ["Google Gemini", { developer: "Google", description: "The Google Gemini app is an AI assistant that can help supercharge your creativity and productivity.", filename:"Google Gemini.webp",detailedInfo:"The Google Gemini app collects a broad and significant range of user data. This includes account details (such as your Google Account information), usage data (all prompts, responses, and activity within Gemini), device information (device type, operating system, IP address), and location data if enabled. Gemini may also collect language preferences, feedback, and content you share or upload through the app. By default, your Gemini activity is saved to your Google Account and retained for up to 18 months, but you can adjust this retention period or disable activity tracking. Even if you turn off Gemini Apps Activity, your conversations may be stored for up to 72 hours for security purposes. Google does not sell your personal data, but it shares information with third parties for analytics, service improvement, and advertising across its platforms. Data from Gemini may also be used to improve AI models unless you opt out, and Google’s privacy policy allows for broad use of collected data across its services.<br><br>To reduce data collection in Gemini, disable Gemini Apps Activity, set auto-delete for your activity to the shortest period, limit permissions (such as location and microphone), avoid sharing sensitive or personal information, and regularly review your privacy settings. Using Gemini without logging in, or through a privacy-focused browser, can further minimize tracking and data sharing."}],
  ["Amazon Shopping", { developer: "AMZN Mobile LLC", description: "Amazon Shopping offers app-only benefits to help make shopping on Amazon faster and easier. Browse, view product details, read reviews, and purchase millions of products. Amazon delivers to 100+ countries in as quickly as 3-5 days.", filename:"Amazon.webp",detailedInfo:"The Amazon Shopping app collects a large amount of personal data. This includes account details (such as your name, email, phone number, address, and payment information), usage data (purchase history, search and browsing activity, reviews, and interactions within the app), device information (device type, operating system, IP address, and unique identifiers), location data (including precise location if enabled), and content you share (such as photos, ratings, and messages). The app may also collect sensitive data like contacts, microphone, and camera access if you grant permission. Amazon shares user data with affiliates, service providers, and third parties for analytics, marketing, advertising, fraud prevention, and service improvement, but states it does not sell your personal information to others. However, data is widely used for personalized recommendations and targeted ads across Amazon’s platforms.<br><br>To reduce data collection and tracking in the Amazon Shopping app, limit app permissions (especially for location, contacts, and camera), avoid saving sensitive information, regularly review your privacy settings, opt out of marketing communications, and clear your search and purchase history. Using Amazon’s website with privacy-focused browsers and tracker blockers can further minimize data sharing and tracking."}],
  ["Bible Chat: Daily Devotional", { developer: "Bookvitals APP SRL", description: "Begin your day with inspiration right on your home screen. Our new Daily Prayer Widgets offer personalized prayers and scripture tailored to your spiritual journey, making faith an integral part of your daily routine. Customize your faith with various designs and themes to match your personal style or mood.", filename:"Bible Chat.webp",detailedInfo:"The Bible Chat: Daily Devotional app collects a broad range of personal information. This includes account details (such as email, username, church affiliation, religious denomination, and age range), usage data (log files, browsing and search history, links clicked, pages viewed, and dates/times of access), device information (device type, operating system, IP address, browser, and cookies), and specific location data if enabled. The app also collects all content you share or input, including text, files, images, and metadata, as well as communication information (messages sent to support or social media) and social networking data if you connect accounts like Facebook or Google. Bible Chat may share data with third parties for analytics, personalization, or marketing with your consent, and integrates with outside platforms whose privacy policies may differ. The app does not sell your personal information outright, but sharing for marketing or analytics could be considered a sale under some privacy laws.<br><br>Privacy-conscious alternatives include using offline devotional books, open-source Bible study apps, or web-based platforms that do not require account creation or collect minimal data. To reduce data collection in Bible Chat, avoid linking social media accounts, limit permissions (especially for location and contacts), use the app without sharing sensitive details, and regularly review and update your privacy settings."}],
  ["PayPal - Pay, Send, Save", { developer: "PayPal, Inc.", description: "PayPal is a smart and secure way to shop in-store and online, earn cash back on brands you love, send money to friends and much more. Get started in the app.", filename:"Paypal.webp" }],
  ["Ticketmaster－Buy, Sell Tickets", { developer: "Ticketmaster", description: "The Ticketmaster app makes it easier to buy, sell, and get into the very best of live entertainment - so you can get on with making memories that last. We give you unparalleled access to thousands of venues, artists, theater and sports events.", filename:"Ticketmaster.webp" }],
  ["Zoom Workplace", { developer: "Zoom Communications, Inc.", description: "Reimagine teamwork with Zoom Workplace, an AI-first, open collaboration platform that combines team chat, meetings, phone*, whiteboard, calendar, mail, docs, and more. Use Zoom Workplace for iOS with any free or paid Zoom license.", filename:"Zoom.webp" }],
  ["Google Meet", { developer: "Google", description: "Google Meet is a high-quality video calling app designed to help you have meaningful and fun interactions with your friends, family, colleagues, and classmates, wherever they are. Meet lets you connect in whatever way works for you: Call someone spontaneously, schedule time together, or send a video message that they can watch and respond to later.", filename:"Google Meet.webp" }],
  ["Google Drive", { developer: "Google", description: "Google Drive, part of Google Workspace, lets you securely store, intelligently organize and collaborate on files and folders from anywhere, on any device.", filename:"Google Drive.webp" }],
  ["Google Docs ", { developer: "Google", description: "Create, edit, and collaborate on online documents with the Google Docs app. Work together in real time. Share documents with your team. Edit, comment, and add action items in real time. Never lose changes or previous versions of your document with version history.", filename:"Google Docs.webp" }],
  ["Life360: Stay Connected & Safe", { developer: "Life360", description: "Loving someone means worrying constantly. Life360 helps you know they're safe, no horror-movie plot twists required. Stay connected and secure with Life360, the ultimate friend and family locator and location-tracking app.", filename:"Life360.webp" }],
  ["Best Buy: Tech drops & deals", { developer: "Best Buy Co., Inc.", description: "Get the best deals on appliances, electronics and more at Best Buy. We've simplified tech shopping, with warp-speed checkout, Curbside Pickup, limited runs, and can't-miss deals. Whether you're in the market for the latest gadgets, electronics or essential appliances, Best Buy provides everything you need at your fingertips.", filename:"Best Buy.webp" }],
  ["Expedia: Hotels, Flights, Cars", { developer: "Expedia, Inc.", description: "TRAVEL PLANNING MADE EASY IN ONE APP Plan, collaborate, book and manage your whole trip, from flights, vacation packages, hotels, car rentals, activities, and more. Find inspiration for your next destination, expert tips and personalized recommendations. Book your flight, hotel and more together to save.*", filename:"Expedia.webp" }],
  ["Airbnb", { developer: "Airbnb, Inc.", description: "THE FASTEST, EASIEST WAY TO AIRBNB Find inspiration, plan a trip with your group, book it, and go. You'll always have access to important trip information. And you'll never miss a beat with instant notifications about your travel plans and messages from your host.", filename:"Airbnb.webp" }],
  ["Discord - Talk, Play, Hang Out", { developer: "Discord, Inc.", description: "Discord is designed for gaming and great for just chilling with friends or building a community. Customize your own space and gather your friends to talk while playing your favorite games, or just hang out.", filename:"Discord.webp" }],
  ["Venmo", { developer: "Venmo", description: "Venmo is the fast, safe, social way to pay and get paid. Join over 83 million people who use the Venmo app today.", filename:"Venmo.webp" }],
  ["Pinterest", { developer: "Pinterest", description: "Pinterest is a place of endless possibilities. You can: - Discover everyday inspiration - Shop styles you love - Try and learn something new Create boards, save Pins and make collages of all your inspiration. Unlock billions of ideas, from fashion tips and easy recipes to DIY projects and fresh ways to redo your space. Creating the life you love? It's Possible.", filename:"Pinterest.webp" }],
  ["T-Life", { developer: "T-Mobile", description: "ONE APP. ALL THE THINGS. Get the latest exclusive perks from T-Mobile Tuesdays, and take advantage of all your Magenta Status benefits. You can also pay your bill, add a line to your account, and track orders straight from the app. And you can manage your account, configure your T-Mobile Home Internet gateway, and more. If you need help with anything, customer care is available at the tap of a button.", filename:"T-Life.webp" }],
  ["Amazon Prime Video", { developer: "AMZN Mobile LLC", description: "Watch movies, TV, and sports, including Amazon Originals like The Boys, The Marvelous Mrs. Maisel, and Tom Clancy's Jack Ryan as well as recommendations just for you.", filename:"AmazonPrimeVideo.webp" }],
  ["Intuit Credit Karma", { developer: "Credit Karma, Inc.", description: "Navigate your unique financial path confidently with help from Credit Karma and make the most of your money.", filename:"Credit Karma.webp" }],
  ["Duolingo - Language Lessons", { developer: "Duolingo", description: "Learn a new language with the world's most-downloaded education app! Duolingo is the fun, free app for learning 40+ languages through quick, bite-sized lessons. Practice speaking, reading, listening, and writing to build your vocabulary and grammar skills.", filename:"Duolingo.webp" }],
  ["Netflix", { developer: "Netflix, Inc.", description: "Looking for the most talked about TV shows and movies from around the world? They're all on Netflix. We've got award-winning series, movies, documentaries, and stand-up specials. And with the mobile app, you get Netflix while you travel, commute, or just take a break.", filesname:"Netflix.webp" }],
  ["Yuka - Food & Cosmetic Scanner", { developer: "Yuca", description: "Yuka is a free mobile app that allows you to scan the barcodes of food and personal care products and instantly see their impact on your health. A rating and detailed information help you understand the analysis of each product.", filename:"Yuka.webp" }],
  ["Snapchat", { developer: "Snap, Inc.", description: "Snapchat is a fast and fun way to share the moment with your friends and family SNAP. Snapchat opens right to the Camera — just tap to take a photo, or press and hold for video. Express yourself with Lenses, Filters, Bitmoji and more! Try out new Lenses daily created by the Snapchat community!", filename:"Snapchat.webp" }],
  ["MyChart", { developer: "Epic", description: "MyChart puts your health information in the palm of your hand and helps you conveniently manage care for yourself and your family members.", filename:"MyChart.webp" }],
  ["Capital One Mobile", { developer: "Capital One", description: "What's on the Capital One Mobile app? All of your accounts, and so much more. Whether you're out in the world or feeling right at home, you can manage your money with ease: - View balances and export statements - Pay bills and take care of loans - Check in on your credit with CreditWise - Activate a credit or debit card when you need it - Redeem rewards on the go - Send and receive money with friends and family using Zelle.", filename:"Capital One Mobile.webp" }],
  ["DramaBox - Stream Drama Shorts", { developer: "STORYMATRIX PTE. LTD.", description: "Looking for something to watch during your daily commute, lunch break, or just to unwind after a long day? Look no further than our Dramabox! With our app, you can access a huge selection of high-quality content from some of the best creators out there. From indie films to award-winning TV series, we've got something for everyone. And with new content added regularly, you'll always have something fresh to watch.", filename:"DramaBox.webp" }],
  ["Grok", { developer: "xAI", description: "Grok is an AI-powered assistant, developed by xAI, designed to be maximally truthful, useful, and curious. Get answers to any question, generate striking images, and upload pictures to gain a deeper understanding of your world. With Grok, the universe is in your hands!", filename:"Grok.webp" }],
  ["Tubi: Movies & Live TV", { developer: "Tubi, Inc", description: "Nice to meet you, we're Tubi. We're more than a completely fee-free streamer with the largest library in the entire streaming universe. We're entertainment fiends and collectors, and never judgers. So, get comfy and settle into whatever you're feeling. It's about to get good.", filename:"Tubi.webp" }],
  ["LinkedIn: Network & Job Finder", { developer: "LinkedIn Corporation", description: "Welcome professionals! The key to getting in is getting started. Begin your career journey with LinkedIn today. Are you searching for the right job opportunities to advance your career? LinkedIn is one of the largest social networking apps for online job searches that also provides content that can help you grow.", filename:"LinkedIn.webp" }],
  ["X", { developer: "X Corp.", description: "The X app is the trusted global digital town square for everyone.", filename:"X.webp" }],
  ["Cleanup: Phone Storage Cleaner", { developer: "Codeway Dijital Hizmetler Anonim Sirketi", description: "LET'S FACE IT: CLEANING UP YOUR PHOTO LIBRARY IS SO BORING! Cleanup is here to make this process easy, fun & safe. CLEAN UP YOUR GALLERY IN NO TIME Swipe left — to get rid of unwanted photos/duplicates Swipe right — to keep the memories that actually matter to you You'll be surprised to see how many unnecessary photos you've been keeping in your gallery!", filename:"CleanUp.webp" }],
  ["Reddit", { developer: "Reddit", description: "Welcome to Reddit, the heart of the internet. Reddit is a social network with something for everyone: trending topics, diverse discussions, and engaging communities and comment threads. Redditors have authentic and interesting conversations around all sorts of curated content. You'll find gaming communities, bloggers, meme-makers, fandoms, travel enthusiasts, support groups, AI forums, news junkies, artists, and creators of all types.", filename:"Reddit.webp" }],
  ["The Roku App (Official)", { developer: "ROKU INC", description: "Get to know the must-have app for streamers Use the free Roku® mobile app to: Control your Roku devices with a convenient remote, Use your voice or keyboard to quickly search for entertainment, Enjoy private listening with headphones, Stream free movies, live TV, and more on the go with The Roku Channel, Cast media files from your phone, like videos and photos, to your TV, Add and launch channels on your Roku devices, Enter text on your Roku device easier with your mobile keyboard", filename:"Roku.webp" }],
  ["Lyft", { developer: "Lyft, Inc.", description: "Get where you're going with Lyft. Whether you're catching a flight, going out for the night, commuting to the office, or running errands in a rush, the Lyft app offers you multiple ways to get there.", filename:"Lyft.webp" }],
  ["Flip: Watch, Create, Shop", { developer: "Humans Inc.", description: "Welcome to the Flip Side. Where social meets shopping, and trust takes center stage. Flip isn't just an app - it's a community-powered platform where creativity thrives and trust fuels every interaction. Real people share their honest stories about experiences and products they love (or don't). Here, you don't just scroll; you get rewarded for it, you create, connect, and earn. And when you're ready, you can shop the products you love, right when you love them - all in a community you trust.", filename:"Flip.webp" }],
  ["ReelShort - Stream Drama & TV", { developer: "NewLeaf Publishing", description: "Never have enough time to finish a movie anymore? Tired of paying for subscriptions that you don't use? Watch ReelShort - Every Second is Drama. Tired of never finishing a movie or paying for unused subscriptions? Watch ReelShort — Every Second is Drama", filename:"ReelShort.webp" }],
  ["Microsoft 365 Copilot", { developer: "Microsoft Corporation", description: "The Microsoft 365 Copilot app is your everyday productivity app for work and life that helps you find and edit files, scan documents, and create content on the go with access to Microsoft 365 Copilot Chat*, Word, Excel, PowerPoint, and PDFs all in one app.", filename:"Microsoft Copilot.webp" }],
  ["Zelle", { developer: "Early Warning Services, LLC", description: "Zelle® is a great way to send money to friends and family, even if they bank somewhere different than you do. More than 2,200 banks and credit unions across the U.S. now offer Zelle® through their mobile app or online banking. The Zelle® app will help you locate a bank or credit union that offers Zelle®. And for those who enrolled with Zelle® through the Zelle® app, you can view your historical Zelle® activity but can no longer send or receive money through the Zelle® app.", filename:"Zelle.webp" }],
  ["Google Sheets", { developer: "Google", description: "Create, edit, and collaborate on spreadsheets with the Google Sheets app. ", filename:"Google Sheets.webp" }],
  ["UKG Pro", { developer: "UKG INC.", description: "Say hello to the mobile work experience built to help you thrive at work. Simple and intuitive by design, the UKG Pro mobile app gives you instant, secure access to relevant employee information, tools, and insights helping you stay productive and engaged on the go. From clocking time and flexing schedules to checking pay and setting aspirational goals, you'll discover how delightful work can be.", filename:"UKG Pro.webp" }],
  ["Taco Bell Fast Food & Delivery", { developer: "Taco Bell", description: "Download the official Taco Bell® app and your taste buds will officially thank you. Earn points on every qualifying order and reward yourself with free food. Gain access to exclusives only available on the app. Order tacos for delivery or pickup", filename:"Taco Bell.webp" }],
  ["Etsy: Shop Home, Style & More", { developer: "Etsy, Inc.", description: "Shop from Etsy sellers across every state in the US! From vintage treasures to handmade jewelry, or original home goods — discover unique finds for every trend, style and gifting moment with the Etsy app. Get deals on one-of-a-kind items from small shops and stay up to date on offers from your favorite sellers with notifications. No matter your budget or what you're looking for, Etsy has it! Chat with sellers, instantly purchase finds, and track your orders—all in the app—for a seamless shopping experience.", filename:"Etsy.webp" }],
  ["NetShort - Popular Dramas & TV ", { developer: "NETSTORY PTE. LTD.", description: "Welcome to NetShort, a next-generation HD streaming platform where we offer exclusive vertical TV programming. Our goal is to change how you watch movies, allowing you to enjoy mini-series up to one minute long anytime, anywhere. Whether you're at home or on the go, NetShort lets you watch the most popular mini-series, providing an immersive viewing experience. Join us today!", filename:"NetShort.webp" }],
  ["Starbucks", { developer: "Starbucks Coffee Company", description: "Ordering ahead is just a download away. Get the Starbucks® app for an easier, more rewarding way to enjoy your faves. Why wait?", filename:"Starbucks.webp" }],
  ["Waze Navigation & Live Traffic", { developer: "Waze Inc.", description: "Know what's ahead on the road with the help from other drivers. Waze is a live map that harnesses the local knowledge of tens of millions of drivers around the world. Drivers safely and confidently reach their everyday destinations thanks to Waze map's GPS navigation, live traffic updates, real-time safety alerts (including construction, accidents, crashes, police, potholes, and more), and accurate ETAs.", filename:"Waze.webp" }],
  ["Progressive", { developer: "Progressive Insurance", description: "Easy access to your insurance, whenever and wherever you need it.", filename:"Progressive.webp" }],
  ["Edits, an Instagram app", { developer: "Instagram, Inc.", description: "Make videos you're proud to share with Edits, the new video creation app from Instagram. Edits is a free video editor that makes it easy for creators to turn their ideas into videos, right on their phone. It has all the tools you need to support your creation process, all in one place.", filename:"Edits, an instagram app.webp" }],
  ["DoorDash - Dasher", { developer: "DoorDash, Inc.", description: "Enjoy the freedom to be your own boss and earn money on your schedule. Plus, get 100% of your tips, always.", filename:"Doordash Dasher.webp" }],
  ["MLB Ballpark", { developer: "MLB", description: "The MLB Ballpark app is your mobile companion when visiting your favorite Major League Baseball ballparks. The official MLB Ballpark application perfectly complements and personalizes your trip with digital ticketing functionality, mobile check-in, offers, rewards and exclusive content.", filename:"MLB Ballpark.webp" }],
  ["Booking.com: Hotels & Travel", { developer: "Booking.com", description: "Save on your next trip with the Booking.com app! Find great hotel or apartment deals and book in just a few minutes. You can also book flights, rental cars, and more through the app.", filename:"Bookingcom.webp" }],
  ["American Airlines", { developer: "American Airlines", description: "With the American Airlines app, you're covered with the information you need exactly when you need it. Curious about traffic to the airport? Need a mobile boarding pass? Wondering where the closest Admirals Club® lounge is? All of this info and more is available at your fingertips.", filename:"American Airlines.webp" }],
  ["Google Translate", { developer: "Google", description: "Translate between up to 249 languages. Feature support varies by language. Text: Translate between languages by typing. Offline: Translate with no internet connection. Instant camera translation: Translate text in images instantly by just pointing your camera", filename:"Google Translate.webp" }],
  ["Fly Delta", { developer: "Delta Air Lines, Inc.", description: "Welcome to Fly Delta, Delta's award winning iOS app. With our dynamic Today screen which provides quick access to your boarding pass and other important day-of-travel information, Fly Delta makes travel easier than ever before.", filename:"Fly Delta.webp" }],
  [" online shopping & selling", { developer: " Inc.", description: "Life's easier in the eBay app—buy, sell & browse millions of items on the go. Discover exclusive deals, every single day. Enjoy a truly personalized and smooth way to buy & sell with eBay.", filename:"ebay.webp" }],
  ["Google Photos: Backup & Edit", { developer: "Google", description: "Google Photos is a smarter home for all your photos and videos, made for the way you take photos today.", filename:"GooglePhotos.webp" }],
  ["Alibaba.com", { developer: "杭州阿里巴巴广告有限公司", description: "Alibaba.com is one of the world's leading B2B ecommerce marketplaces. Our app allows you to source products from global suppliers, all from the convenience of your mobile device.", filename:"Alibaba.webp" }],
  ["SHEIN - Shopping Online", { developer: "ROADGET BUSINESS PTE. LTD.", description: "SHEIN is a fun and ultra-affordable online shopping platform. From fashion apparel to home, beauty, accessories, shoes and pets, plus electronics, tools, office and more, SHEIN is dedicated to meeting all your needs in life. We'll keep you in the loop with push notifications about new drops and more. You can also engage with other SHEIN lovers in real time. With free shippings and free returns policy, hope you have a pleasant journey with SHEIN!", filename:"Shein.webp" }],
  ["ADP Mobile Solutions", { developer: "ADP, Inc", description: "ADP Mobile Solutions provides you with an easy and convenient way to access payroll, time & attendance, benefits, and other vital HR information for you and your team.", filename:"ADP Solutions.webp" }],
  ["VPN - Super Unlimited Proxy", { developer: "Mobile Jump Pte Ltd", description: "Free VPN for iPhone and iPad - protect your privacy on WiFi and hotspots!", filename:"VPNSuperUnlimitedProxy.webp" }],
  ["GroupMe", { developer: "Skype Communications S.a.r.l", description: "GroupMe - the free, simple way to stay in touch with the people who matter most. Family. Roommates. Friends. Coworkers. Teams. Vacations. Greek Life. Bands. Faith Groups. Events.", filename:"GroupMe.webp" }], 
  ["Chase Mobile®: Bank & Invest", { developer: "JPMorgan Chase & Co.", description: "Bank securely with the Chase Mobile® app: send and receive money with Zelle®, deposit checks, monitor credit score, budget and track income & spend. Use J.P. Morgan Wealth Management to plan, invest, & set and track long-terms goals with Wealth Plan.", filename:"Chase Mobile.webp" }],
  ["Disney+", { developer: "Disney", description: "Disney+ is the streaming home of your favorite stories. With beloved movies and series from Disney, Pixar, Marvel, Star Wars, National Geographic, there's always something to explore. Stream the latest movie releases, exclusive Original series, and highly anticipated matchups all in Disney+.", filename:"DisneyPlus.webp" }],
  ["United Airlines", { developer: "United Airlines", description: "Meet the United app. From planning, to booking, to day of travel, we've got you covered.", filename:"UnitedAirlines.webp" }],
  ["Zillow Real Estate & Rentals", { developer: "Zillow.com", description: "Whether you're looking to rent, buy, or sell, Zillow is the all-in-one app for making home real. Personalize your search with up-to-date listings of millions of homes at your fingertips. Save, search, and share listings seamlessly. Utilize our exclusive BuyAbility℠ tool to discover your home-buying budget. Stay updated on the homes that catch your eye and schedule a home tour with a partner agent with expert knowledge of local listings. Download Zillow today and find the home to buy or rent that's right for you.", filename:"Zillow.webp" }],
  ["Google Slides", { developer: "Google", description: "Create, edit, and collaborate on presentations with the Google Slides app.", filename:"Google Slides.webp" }],
  ["YouTube Music", { developer: "Google", description: "Connecting you to the world of music: Music content including live performances, covers, remixes and music content you can't find elsewhere. Thousands of curated playlist across many genres and activities.", filename:"YoutubeMusic.webp" }],
  ["Google Authenticator", { developer: "Google", description: "Google Authenticator adds an extra layer of security to your online accounts by adding a second step of verification when you sign in. This means that in addition to your password, you'll also need to enter a code that is generated by the Google Authenticator app on your phone.", filename:"GoogleAuthenticator.webp" }],
  ["MyFitnessPal: Calorie Counter", { developer: "MyFitnessPal, Inc.", description: "Track progress toward your nutrition, water, fitness, and weight loss goals with MyFitnessPal. This all-in-one food tracker and health app is like having a nutrition coach, meal planner, and food diary with you at all times.", filename:"MyFitnessPal.webp" }],
  ["Lemon8 - Lifestyle Community", { developer: "TikTok Ltd.", description: "Lemon8 is a lifestyle community focused app powered by TikTok, where you can discover and share authentic content on a variety of topics such as beauty, fashion, travel, food, and more. You can edit and share photos with great ease and engage in discussion with like-minded people. Lemon8 offers a space where you can connect, inspire, and support one another.", filename:"Lemon8.webp" }],
  ["Messenger", { developer: "Meta Platforms, Inc.", description: "Messenger is a free messaging app that helps you connect with anyone, anywhere. Stay in touch with your friends and family, explore your interests with people like you, build your community, and share your vibe beyond words, all in one app.", filename:"FacebookMessenger.webp" }],
]);

let index = 0;
const textElement = document.getElementById("slidingText");

function updateText() {
  textElement.classList.remove("sliding-text");
  void textElement.offsetWidth;
  textElement.textContent = messages[index];
  textElement.classList.add("sliding-text");
}

setInterval(() => {
  index = (index + 1) % messages.length;
  updateText();
}, 2000); 

// Function to animate the placeholder text: Search for an app... in the search bar
function animatePlaceholder() {
  const searchInput = document.getElementById('search');
  const placeholderText = "Search for an app...";
  let currentIndex = 0;

  function typeLetter() {
    if (currentIndex <= placeholderText.length) {
      searchInput.setAttribute('placeholder', placeholderText.substring(0, currentIndex));
      currentIndex++;
      setTimeout(typeLetter, 200);
    }
  }

  typeLetter();
}
window.onload = animatePlaceholder;


document.getElementById('search').addEventListener('keypress', function (event) {
  if (event.key === 'Enter') {
    const searchTerm = event.target.value.trim();

    // Dismiss the mobile keyboard by blurring the input field
    event.target.blur();

    if (searchTerm) {
      displayResults(searchTerm);
    }
  }
});

function displayResults(searchTerm) {
  const resultsContainer = document.getElementById('results-container');
  resultsContainer.innerHTML = ''; // Clear previous results

  let foundResults = false;
  appData.forEach((value, appName) => {
    if (appName.toLowerCase().includes(searchTerm.toLowerCase())) {
      foundResults = true;

      const tile = document.createElement('div');
      tile.className = 'result-tile';

      const icon = document.createElement('img');
      icon.className = 'app-icon';
      icon.src = `./App Icons/${value.filename}`;
      icon.alt = `${appName} icon`;

      const content = document.createElement('div');
      content.className = 'result-content';

      const title = document.createElement('div');
      title.className = 'result-title';
      title.textContent = appName;

      const developer = document.createElement('div');
      developer.className = 'result-developer';
      developer.textContent = `Developer: ${value.developer}`;

      const description = document.createElement('div');
      description.className = 'result-description';
      description.textContent = value.description;

      const detailedInfo = document.createElement('div');
      detailedInfo.className = 'result-detailed-info';

      const detailedInfoTitle = document.createElement('div');
      detailedInfoTitle.className = 'detailed-info-title';
      detailedInfoTitle.textContent = 'Privacy Information';

      const detailedInfoText = document.createElement('div');
      detailedInfoText.className = 'detailed-info-text';
      detailedInfoText.innerHTML = value.detailedInfo || "Privacy info not yet available.";

      // Create disclaimer section
      const disclaimerSection = document.createElement('div');
      disclaimerSection.className = 'disclaimer-section';
      disclaimerSection.innerHTML = `
        <div class="disclaimer-header">
          <span class="disclaimer-icon">ⓘ</span>
          <span class="disclaimer-text">Privana summaries may contain mistakes.</span>
        </div>
        <div class="disclaimer-explanation">
          <p>While we strive for accuracy, our summaries may not reflect the most current privacy policies. App privacy practices are summarized with a LLM, which may make mistakes or misrepresentations. We recommend checking the official privacy policy of any app for the most up-to-date information.</p>
        </div>
      `;

      detailedInfo.appendChild(detailedInfoTitle);
      detailedInfo.appendChild(disclaimerSection);
      detailedInfo.appendChild(detailedInfoText);

      detailedInfo.style.display = 'none';

      content.appendChild(title);
      content.appendChild(developer);
      content.appendChild(description);

      const closeButton = document.createElement('button');
      closeButton.className = 'close-button';
      closeButton.textContent = 'X';

      tile.addEventListener('click', function () {
        tile.classList.add('expanded');
        detailedInfo.style.display = 'block';
        
        // Initialize disclaimer functionality for this tile
        initializeDisclaimerForTile(disclaimerSection);
      });

      closeButton.addEventListener('click', function (event) {
        event.stopPropagation();
        tile.classList.remove('expanded');
        detailedInfo.style.display = 'none';
      });

      tile.appendChild(icon);
      tile.appendChild(content);
      tile.appendChild(detailedInfo); 
      tile.appendChild(closeButton);

      resultsContainer.appendChild(tile);
    }
  });

  if (!foundResults) {
    const noResults = document.createElement('div');
    noResults.className = 'no-results';
    noResults.innerHTML = 'No apps found matching your search. Suggest an app to add <a href="https://forms.gle/mhHYBYPjpE2DfhuJ8" class="suggest-link">here</a>!';
    resultsContainer.appendChild(noResults);
  }
}

// Disclaimer functionality for expanded tiles
function initializeDisclaimerForTile(disclaimerSection) {
  const disclaimerHeader = disclaimerSection.querySelector('.disclaimer-header');
  const disclaimerIcon = disclaimerSection.querySelector('.disclaimer-icon');
  const disclaimerExplanation = disclaimerSection.querySelector('.disclaimer-explanation');
  
  if (disclaimerHeader && disclaimerIcon && disclaimerExplanation) {
    // Remove any existing event listeners
    disclaimerHeader.removeEventListener('click', disclaimerHeader.clickHandler);
    
    // Add new event listener
    disclaimerHeader.clickHandler = function() {
      const isExpanded = disclaimerExplanation.classList.contains('expanded');
      
      if (isExpanded) {
        // Collapse
        disclaimerExplanation.classList.remove('expanded');
        disclaimerIcon.classList.remove('expanded');
      } else {
        // Expand
        disclaimerExplanation.classList.add('expanded');
        disclaimerIcon.classList.add('expanded');
      }
    };
    
    disclaimerHeader.addEventListener('click', disclaimerHeader.clickHandler);
  }
}

// Welcome Overlay Functionality
function showWelcomeOverlay() {
  const overlay = document.getElementById('welcome-overlay');
  if (overlay) {
    overlay.classList.remove('hidden');
  }
}

function hideWelcomeOverlay() {
  const overlay = document.getElementById('welcome-overlay');
  if (overlay) {
    overlay.classList.add('hidden');
  }
}

function hasVisitedBefore() {
  return localStorage.getItem('privana-visited') === 'true';
}

function markAsVisited() {
  localStorage.setItem('privana-visited', 'true');
}

// Initialize welcome overlay on page load
document.addEventListener('DOMContentLoaded', function() {
  // Check if this is the user's first visit
  if (!hasVisitedBefore()) {
    // Show overlay after a short delay to ensure smooth loading
    setTimeout(() => {
      showWelcomeOverlay();
    }, 500);
  }
  
  // Add event listener for continue button
  const continueBtn = document.getElementById('continue-btn');
  if (continueBtn) {
    continueBtn.addEventListener('click', function() {
      markAsVisited();
      hideWelcomeOverlay();
    });
  }
  
  // Also allow closing by clicking outside the content
  const overlay = document.getElementById('welcome-overlay');
  if (overlay) {
    overlay.addEventListener('click', function(event) {
      if (event.target === overlay) {
        markAsVisited();
        hideWelcomeOverlay();
      }
    });
  }
});
